/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cminus.node;

import Cminus.analysis.*;

@SuppressWarnings("nls")
public final class AADeclaration extends PDeclaration
{
    private PVarDeclaration _varDeclaration_;

    public AADeclaration()
    {
        // Constructor
    }

    public AADeclaration(
        @SuppressWarnings("hiding") PVarDeclaration _varDeclaration_)
    {
        // Constructor
        setVarDeclaration(_varDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AADeclaration(
            cloneNode(this._varDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAADeclaration(this);
    }

    public PVarDeclaration getVarDeclaration()
    {
        return this._varDeclaration_;
    }

    public void setVarDeclaration(PVarDeclaration node)
    {
        if(this._varDeclaration_ != null)
        {
            this._varDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varDeclaration_ == child)
        {
            this._varDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varDeclaration_ == oldChild)
        {
            setVarDeclaration((PVarDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
