/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cminus.node;

import Cminus.analysis.*;

@SuppressWarnings("nls")
public final class AALocalDeclarations extends PLocalDeclarations
{
    private PLocalDeclarations _localDeclarations_;
    private PVariableDeclaration _variableDeclaration_;

    public AALocalDeclarations()
    {
        // Constructor
    }

    public AALocalDeclarations(
        @SuppressWarnings("hiding") PLocalDeclarations _localDeclarations_,
        @SuppressWarnings("hiding") PVariableDeclaration _variableDeclaration_)
    {
        // Constructor
        setLocalDeclarations(_localDeclarations_);

        setVariableDeclaration(_variableDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AALocalDeclarations(
            cloneNode(this._localDeclarations_),
            cloneNode(this._variableDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAALocalDeclarations(this);
    }

    public PLocalDeclarations getLocalDeclarations()
    {
        return this._localDeclarations_;
    }

    public void setLocalDeclarations(PLocalDeclarations node)
    {
        if(this._localDeclarations_ != null)
        {
            this._localDeclarations_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._localDeclarations_ = node;
    }

    public PVariableDeclaration getVariableDeclaration()
    {
        return this._variableDeclaration_;
    }

    public void setVariableDeclaration(PVariableDeclaration node)
    {
        if(this._variableDeclaration_ != null)
        {
            this._variableDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variableDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._localDeclarations_)
            + toString(this._variableDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._localDeclarations_ == child)
        {
            this._localDeclarations_ = null;
            return;
        }

        if(this._variableDeclaration_ == child)
        {
            this._variableDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._localDeclarations_ == oldChild)
        {
            setLocalDeclarations((PLocalDeclarations) newChild);
            return;
        }

        if(this._variableDeclaration_ == oldChild)
        {
            setVariableDeclaration((PVariableDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
