/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cminus.node;

import Cminus.analysis.*;

@SuppressWarnings("nls")
public final class AASimpleExpression extends PSimpleExpression
{
    private PSimpleExpression _simpleExpression_;
    private PRelationalOperator _relationalOperator_;
    private PExp _exp_;

    public AASimpleExpression()
    {
        // Constructor
    }

    public AASimpleExpression(
        @SuppressWarnings("hiding") PSimpleExpression _simpleExpression_,
        @SuppressWarnings("hiding") PRelationalOperator _relationalOperator_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setSimpleExpression(_simpleExpression_);

        setRelationalOperator(_relationalOperator_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AASimpleExpression(
            cloneNode(this._simpleExpression_),
            cloneNode(this._relationalOperator_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAASimpleExpression(this);
    }

    public PSimpleExpression getSimpleExpression()
    {
        return this._simpleExpression_;
    }

    public void setSimpleExpression(PSimpleExpression node)
    {
        if(this._simpleExpression_ != null)
        {
            this._simpleExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpleExpression_ = node;
    }

    public PRelationalOperator getRelationalOperator()
    {
        return this._relationalOperator_;
    }

    public void setRelationalOperator(PRelationalOperator node)
    {
        if(this._relationalOperator_ != null)
        {
            this._relationalOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relationalOperator_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpleExpression_)
            + toString(this._relationalOperator_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpleExpression_ == child)
        {
            this._simpleExpression_ = null;
            return;
        }

        if(this._relationalOperator_ == child)
        {
            this._relationalOperator_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpleExpression_ == oldChild)
        {
            setSimpleExpression((PSimpleExpression) newChild);
            return;
        }

        if(this._relationalOperator_ == oldChild)
        {
            setRelationalOperator((PRelationalOperator) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
