/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cminus.node;

import Cminus.analysis.*;

@SuppressWarnings("nls")
public final class AAStatementWithElse extends PStatementWithElse
{
    private PAttributionStatement _attributionStatement_;

    public AAStatementWithElse()
    {
        // Constructor
    }

    public AAStatementWithElse(
        @SuppressWarnings("hiding") PAttributionStatement _attributionStatement_)
    {
        // Constructor
        setAttributionStatement(_attributionStatement_);

    }

    @Override
    public Object clone()
    {
        return new AAStatementWithElse(
            cloneNode(this._attributionStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAStatementWithElse(this);
    }

    public PAttributionStatement getAttributionStatement()
    {
        return this._attributionStatement_;
    }

    public void setAttributionStatement(PAttributionStatement node)
    {
        if(this._attributionStatement_ != null)
        {
            this._attributionStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attributionStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._attributionStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._attributionStatement_ == child)
        {
            this._attributionStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._attributionStatement_ == oldChild)
        {
            setAttributionStatement((PAttributionStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
