/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cminus.node;

import Cminus.analysis.*;

@SuppressWarnings("nls")
public final class ABStatementWithElse extends PStatementWithElse
{
    private PCompoundStatement _compoundStatement_;

    public ABStatementWithElse()
    {
        // Constructor
    }

    public ABStatementWithElse(
        @SuppressWarnings("hiding") PCompoundStatement _compoundStatement_)
    {
        // Constructor
        setCompoundStatement(_compoundStatement_);

    }

    @Override
    public Object clone()
    {
        return new ABStatementWithElse(
            cloneNode(this._compoundStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABStatementWithElse(this);
    }

    public PCompoundStatement getCompoundStatement()
    {
        return this._compoundStatement_;
    }

    public void setCompoundStatement(PCompoundStatement node)
    {
        if(this._compoundStatement_ != null)
        {
            this._compoundStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compoundStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._compoundStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._compoundStatement_ == child)
        {
            this._compoundStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._compoundStatement_ == oldChild)
        {
            setCompoundStatement((PCompoundStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
