/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cminus.node;

import Cminus.analysis.*;

@SuppressWarnings("nls")
public final class ADStatementWithElse extends PStatementWithElse
{
    private PIfElseStatement2 _ifElseStatement2_;

    public ADStatementWithElse()
    {
        // Constructor
    }

    public ADStatementWithElse(
        @SuppressWarnings("hiding") PIfElseStatement2 _ifElseStatement2_)
    {
        // Constructor
        setIfElseStatement2(_ifElseStatement2_);

    }

    @Override
    public Object clone()
    {
        return new ADStatementWithElse(
            cloneNode(this._ifElseStatement2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADStatementWithElse(this);
    }

    public PIfElseStatement2 getIfElseStatement2()
    {
        return this._ifElseStatement2_;
    }

    public void setIfElseStatement2(PIfElseStatement2 node)
    {
        if(this._ifElseStatement2_ != null)
        {
            this._ifElseStatement2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifElseStatement2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifElseStatement2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifElseStatement2_ == child)
        {
            this._ifElseStatement2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifElseStatement2_ == oldChild)
        {
            setIfElseStatement2((PIfElseStatement2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
