/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cminus.node;

import Cminus.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private PDeclarationList _declarationList_;

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") PDeclarationList _declarationList_)
    {
        // Constructor
        setDeclarationList(_declarationList_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneNode(this._declarationList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public PDeclarationList getDeclarationList()
    {
        return this._declarationList_;
    }

    public void setDeclarationList(PDeclarationList node)
    {
        if(this._declarationList_ != null)
        {
            this._declarationList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declarationList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declarationList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declarationList_ == child)
        {
            this._declarationList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declarationList_ == oldChild)
        {
            setDeclarationList((PDeclarationList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
