/* This file was generated by SableCC (http://www.sablecc.org/). */

package Cminus.lexer;

import java.io.*;
import Cminus.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                                case 0: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInt(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturn(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVoid(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNum(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStringValue(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSlash(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAsterisk(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLessThan(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLessEqual(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGreatThan(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGreatEqual(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEqual(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDifferent(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAttribution(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeftPar(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightPar(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeftBracket(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightBracket(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeftBrace(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightBrace(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOpenComment(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCloseComment(line, pos); }
    Token new31(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlockComment(text, line, pos); }
    Token new32(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSpace(text, line, pos); }
    Token new33(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEndLine(text, line, pos); }
    Token new34(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLineComment(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {47, 47, 13}, {48, 57, 14}, {59, 59, 15}, {60, 60, 16}, {61, 61, 17}, {62, 62, 18}, {65, 90, 19}, {91, 91, 20}, {93, 93, 21}, {97, 100, 19}, {101, 101, 22}, {102, 104, 19}, {105, 105, 23}, {106, 113, 19}, {114, 114, 24}, {115, 115, 25}, {116, 117, 19}, {118, 118, 26}, {119, 119, 27}, {120, 122, 19}, {123, 123, 28}, {125, 125, 29}, },
            {{9, 9, 1}, {32, 32, 4}, },
            {{10, 10, 2}, {13, 13, 30}, },
            {{10, 13, -2}, },
            {{9, 32, -3}, },
            {{61, 61, 31}, },
            {{0, 33, 32}, {34, 34, 33}, {35, 91, 32}, {92, 92, 34}, {93, 65535, 32}, },
            {},
            {},
            {{47, 47, 35}, },
            {},
            {},
            {},
            {{42, 42, 36}, {47, 47, 37}, },
            {{48, 57, 14}, },
            {},
            {{61, 61, 38}, },
            {{61, 61, 39}, },
            {{61, 61, 40}, },
            {{65, 90, 19}, {97, 122, 19}, },
            {},
            {},
            {{65, 90, 19}, {97, 107, 19}, {108, 108, 41}, {109, 122, 19}, },
            {{65, 90, 19}, {97, 101, 19}, {102, 102, 42}, {103, 109, 19}, {110, 110, 43}, {111, 122, 19}, },
            {{65, 90, 19}, {97, 100, 19}, {101, 101, 44}, {102, 122, 19}, },
            {{65, 90, 19}, {97, 115, 19}, {116, 116, 45}, {117, 122, 19}, },
            {{65, 90, 19}, {97, 110, 19}, {111, 111, 46}, {112, 122, 19}, },
            {{65, 90, 19}, {97, 103, 19}, {104, 104, 47}, {105, 122, 19}, },
            {},
            {},
            {{10, 13, -2}, },
            {},
            {{0, 65535, -8}, },
            {},
            {{0, 33, 32}, {34, 34, 48}, {35, 65535, -8}, },
            {},
            {{0, 41, 49}, {42, 42, 50}, {43, 46, 49}, {48, 65535, 49}, },
            {{0, 9, 51}, {10, 10, 52}, {11, 12, 51}, {13, 13, 53}, {14, 65535, 51}, },
            {},
            {},
            {},
            {{65, 90, 19}, {97, 114, 19}, {115, 115, 54}, {116, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 115, -27}, {116, 116, 55}, {117, 122, 19}, },
            {{65, 115, -27}, {116, 116, 56}, {117, 122, 19}, },
            {{65, 90, 19}, {97, 113, 19}, {114, 114, 57}, {115, 122, 19}, },
            {{65, 90, 19}, {97, 104, 19}, {105, 105, 58}, {106, 122, 19}, },
            {{65, 104, -48}, {105, 105, 59}, {106, 122, 19}, },
            {{0, 65535, -8}, },
            {{0, 65535, -38}, },
            {{47, 47, 60}, },
            {{0, 65535, -39}, },
            {{13, 13, 61}, },
            {},
            {{65, 100, -26}, {101, 101, 62}, {102, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 90, 19}, {97, 116, 19}, {117, 117, 63}, {118, 122, 19}, },
            {{65, 104, -48}, {105, 105, 64}, {106, 122, 19}, },
            {{65, 90, 19}, {97, 99, 19}, {100, 100, 65}, {101, 122, 19}, },
            {{65, 107, -24}, {108, 108, 66}, {109, 122, 19}, },
            {},
            {},
            {{65, 122, -21}, },
            {{65, 113, -47}, {114, 114, 67}, {115, 122, 19}, },
            {{65, 90, 19}, {97, 109, 19}, {110, 110, 68}, {111, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 100, -26}, {101, 101, 69}, {102, 122, 19}, },
            {{65, 109, -66}, {110, 110, 70}, {111, 122, 19}, },
            {{65, 90, 19}, {97, 102, 19}, {103, 103, 71}, {104, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 122, -21}, },
            {{65, 122, -21}, },
        }
        { // COMMENT
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {47, 47, 13}, {48, 57, 14}, {59, 59, 15}, {60, 60, 16}, {61, 61, 17}, {62, 62, 18}, {65, 90, 19}, {91, 91, 20}, {93, 93, 21}, {97, 100, 19}, {101, 101, 22}, {102, 104, 19}, {105, 105, 23}, {106, 113, 19}, {114, 114, 24}, {115, 115, 25}, {116, 117, 19}, {118, 118, 26}, {119, 119, 27}, {120, 122, 19}, {123, 123, 28}, {125, 125, 29}, },
            {{9, 9, 1}, {32, 32, 4}, },
            {{10, 10, 2}, {13, 13, 30}, },
            {{10, 13, -2}, },
            {{9, 32, -3}, },
            {{61, 61, 31}, },
            {{0, 33, 32}, {34, 34, 33}, {35, 91, 32}, {92, 92, 34}, {93, 65535, 32}, },
            {},
            {},
            {{47, 47, 35}, },
            {},
            {},
            {},
            {{42, 42, 36}, {47, 47, 37}, },
            {{48, 57, 14}, },
            {},
            {{61, 61, 38}, },
            {{61, 61, 39}, },
            {{61, 61, 40}, },
            {{65, 90, 19}, {97, 122, 19}, },
            {},
            {},
            {{65, 90, 19}, {97, 107, 19}, {108, 108, 41}, {109, 122, 19}, },
            {{65, 90, 19}, {97, 101, 19}, {102, 102, 42}, {103, 109, 19}, {110, 110, 43}, {111, 122, 19}, },
            {{65, 90, 19}, {97, 100, 19}, {101, 101, 44}, {102, 122, 19}, },
            {{65, 90, 19}, {97, 115, 19}, {116, 116, 45}, {117, 122, 19}, },
            {{65, 90, 19}, {97, 110, 19}, {111, 111, 46}, {112, 122, 19}, },
            {{65, 90, 19}, {97, 103, 19}, {104, 104, 47}, {105, 122, 19}, },
            {},
            {},
            {{10, 13, -2}, },
            {},
            {{0, 65535, -8}, },
            {},
            {{0, 33, 32}, {34, 34, 48}, {35, 65535, -8}, },
            {},
            {{0, 41, 49}, {42, 42, 50}, {43, 46, 49}, {48, 65535, 49}, },
            {{0, 9, 51}, {10, 10, 52}, {11, 12, 51}, {13, 13, 53}, {14, 65535, 51}, },
            {},
            {},
            {},
            {{65, 90, 19}, {97, 114, 19}, {115, 115, 54}, {116, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 115, -27}, {116, 116, 55}, {117, 122, 19}, },
            {{65, 115, -27}, {116, 116, 56}, {117, 122, 19}, },
            {{65, 90, 19}, {97, 113, 19}, {114, 114, 57}, {115, 122, 19}, },
            {{65, 90, 19}, {97, 104, 19}, {105, 105, 58}, {106, 122, 19}, },
            {{65, 104, -48}, {105, 105, 59}, {106, 122, 19}, },
            {{0, 65535, -8}, },
            {{0, 65535, -38}, },
            {{47, 47, 60}, },
            {{0, 65535, -39}, },
            {{13, 13, 61}, },
            {},
            {{65, 100, -26}, {101, 101, 62}, {102, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 90, 19}, {97, 116, 19}, {117, 117, 63}, {118, 122, 19}, },
            {{65, 104, -48}, {105, 105, 64}, {106, 122, 19}, },
            {{65, 90, 19}, {97, 99, 19}, {100, 100, 65}, {101, 122, 19}, },
            {{65, 107, -24}, {108, 108, 66}, {109, 122, 19}, },
            {},
            {},
            {{65, 122, -21}, },
            {{65, 113, -47}, {114, 114, 67}, {115, 122, 19}, },
            {{65, 90, 19}, {97, 109, 19}, {110, 110, 68}, {111, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 100, -26}, {101, 101, 69}, {102, 122, 19}, },
            {{65, 109, -66}, {110, 110, 70}, {111, 122, 19}, },
            {{65, 90, 19}, {97, 102, 19}, {103, 103, 71}, {104, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 122, -21}, },
            {{65, 122, -21}, },
        }
        { // STRING
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {47, 47, 13}, {48, 57, 14}, {59, 59, 15}, {60, 60, 16}, {61, 61, 17}, {62, 62, 18}, {65, 90, 19}, {91, 91, 20}, {93, 93, 21}, {97, 100, 19}, {101, 101, 22}, {102, 104, 19}, {105, 105, 23}, {106, 113, 19}, {114, 114, 24}, {115, 115, 25}, {116, 117, 19}, {118, 118, 26}, {119, 119, 27}, {120, 122, 19}, {123, 123, 28}, {125, 125, 29}, },
            {{9, 9, 1}, {32, 32, 4}, },
            {{10, 10, 2}, {13, 13, 30}, },
            {{10, 13, -2}, },
            {{9, 32, -3}, },
            {{61, 61, 31}, },
            {{0, 33, 32}, {34, 34, 33}, {35, 91, 32}, {92, 92, 34}, {93, 65535, 32}, },
            {},
            {},
            {{47, 47, 35}, },
            {},
            {},
            {},
            {{42, 42, 36}, {47, 47, 37}, },
            {{48, 57, 14}, },
            {},
            {{61, 61, 38}, },
            {{61, 61, 39}, },
            {{61, 61, 40}, },
            {{65, 90, 19}, {97, 122, 19}, },
            {},
            {},
            {{65, 90, 19}, {97, 107, 19}, {108, 108, 41}, {109, 122, 19}, },
            {{65, 90, 19}, {97, 101, 19}, {102, 102, 42}, {103, 109, 19}, {110, 110, 43}, {111, 122, 19}, },
            {{65, 90, 19}, {97, 100, 19}, {101, 101, 44}, {102, 122, 19}, },
            {{65, 90, 19}, {97, 115, 19}, {116, 116, 45}, {117, 122, 19}, },
            {{65, 90, 19}, {97, 110, 19}, {111, 111, 46}, {112, 122, 19}, },
            {{65, 90, 19}, {97, 103, 19}, {104, 104, 47}, {105, 122, 19}, },
            {},
            {},
            {{10, 13, -2}, },
            {},
            {{0, 65535, -8}, },
            {},
            {{0, 33, 32}, {34, 34, 48}, {35, 65535, -8}, },
            {},
            {{0, 41, 49}, {42, 42, 50}, {43, 46, 49}, {48, 65535, 49}, },
            {{0, 9, 51}, {10, 10, 52}, {11, 12, 51}, {13, 13, 53}, {14, 65535, 51}, },
            {},
            {},
            {},
            {{65, 90, 19}, {97, 114, 19}, {115, 115, 54}, {116, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 115, -27}, {116, 116, 55}, {117, 122, 19}, },
            {{65, 115, -27}, {116, 116, 56}, {117, 122, 19}, },
            {{65, 90, 19}, {97, 113, 19}, {114, 114, 57}, {115, 122, 19}, },
            {{65, 90, 19}, {97, 104, 19}, {105, 105, 58}, {106, 122, 19}, },
            {{65, 104, -48}, {105, 105, 59}, {106, 122, 19}, },
            {{0, 65535, -8}, },
            {{0, 65535, -38}, },
            {{47, 47, 60}, },
            {{0, 65535, -39}, },
            {{13, 13, 61}, },
            {},
            {{65, 100, -26}, {101, 101, 62}, {102, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 90, 19}, {97, 116, 19}, {117, 117, 63}, {118, 122, 19}, },
            {{65, 104, -48}, {105, 105, 64}, {106, 122, 19}, },
            {{65, 90, 19}, {97, 99, 19}, {100, 100, 65}, {101, 122, 19}, },
            {{65, 107, -24}, {108, 108, 66}, {109, 122, 19}, },
            {},
            {},
            {{65, 122, -21}, },
            {{65, 113, -47}, {114, 114, 67}, {115, 122, 19}, },
            {{65, 90, 19}, {97, 109, 19}, {110, 110, 68}, {111, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 100, -26}, {101, 101, 69}, {102, 122, 19}, },
            {{65, 109, -66}, {110, 110, 70}, {111, 122, 19}, },
            {{65, 90, 19}, {97, 102, 19}, {103, 103, 71}, {104, 122, 19}, },
            {{65, 122, -21}, },
            {{65, 122, -21}, },
            {{65, 122, -21}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 32, 33, 33, 32, -1, -1, 23, 24, 13, 10, 21, 11, 12, 8, 22, 14, 20, 16, 7, 25, 26, 7, 7, 7, 7, 7, 7, 27, 28, 33, 19, -1, 9, -1, 30, 29, -1, 15, 18, 17, 7, 1, 7, 7, 7, 7, 7, 9, -1, -1, -1, 34, 34, 7, 2, 7, 7, 7, 7, 31, 34, 0, 7, 7, 5, 7, 7, 7, 6, 4, 3, },
        // COMMENT
        {-1, 32, 33, 33, 32, -1, -1, 23, 24, 13, 10, 21, 11, 12, 8, 22, 14, 20, 16, 7, 25, 26, 7, 7, 7, 7, 7, 7, 27, 28, 33, 19, -1, 9, -1, 30, 29, -1, 15, 18, 17, 7, 1, 7, 7, 7, 7, 7, 9, -1, -1, -1, 34, 34, 7, 2, 7, 7, 7, 7, 31, 34, 0, 7, 7, 5, 7, 7, 7, 6, 4, 3, },
        // STRING
        {-1, 32, 33, 33, 32, -1, -1, 23, 24, 13, 10, 21, 11, 12, 8, 22, 14, 20, 16, 7, 25, 26, 7, 7, 7, 7, 7, 7, 27, 28, 33, 19, -1, 9, -1, 30, -1, -1, 15, 18, 17, 7, 1, 7, 7, 7, 7, 7, 9, -1, -1, -1, 34, 34, 7, 2, 7, 7, 7, 7, 31, 34, 0, 7, 7, 5, 7, 7, 7, 6, 4, 3, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMMENT = new State(1);
        public final static State STRING = new State(2);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
